#!/usr/bin/env sh

# Left commit
badCommit=$1
# Right commit
goodCommit=$2

echo '
Searching for the `master` branch based commits.
'

git bisect start "$badCommit" "$goodCommit"

echo '
Skipping the commits inside PRs...
'

prCommits=$(for commit in $(git rev-list "$goodCommit".."$badCommit" --merges --first-parent); do
  git rev-list "$commit"^2 --not "$commit"^
done)

echo "$prCommits" | xargs git bisect skip

echo "
Skipped $(echo "$prCommits" | wc -l) commits inside PRs.
"

echo '
+====

1. Finish Phase I with the classical:

    ```sh
    git bisect run <test-command>
    # OR
    git bisect bad/good
    ```
    Phase I results in particular PR / `master` branch commit.

2. Phase II:

    ```sh
    bisect-pr <commit>
    ```

'
