#!/usr/bin/env sh

# Left commit
badCommit=$1
# Right commit
goodCommit=$2

echo '
Searching for the `master` branch based commits.
'

git bisect start "$badCommit" "$goodCommit"

for commit in $(git rev-list "$goodCommit".."$badCommit" --merges --first-parent); do
  git rev-list "$commit"^2 --not "$commit"^
done | xargs git bisect skip

echo '

1. Continue Phase I with the classical:

    ```sh
    git bisect run <test-command>
    # OR
    git bisect bad/good
    ```
    to find the PR commit.

2. After Phase I is done, start Phase II by:

    ```sh
    bisect-pr <commit>
    ```

'
