#!/usr/bin/env sh

# Left commit
badCommit=$1
# Right commit
goodCommit=$2

git bisect start "$badCommit" "$goodCommit"

for commit in $(git rev-list "$badCommit".."$goodCommit" --merges --first-parent); do
  git rev-list "$commit"^2 --not "$commit"^
done | xargs git bisect skip

echo '

1. Continue the classical:

    ```sh
    git bisect run <test-command>
    # OR
    git bisect bad/good
    ```
    , to find the PR.

2. Case:

    ```sh
    if test -z "$(git show --min-parents=2 --max-parents=2 <commit>)"; then echo <commit>; else echo <continue>; fi
    ```

3. Biseci inside the PR commits:

    ```sh
    git bisect reset
    git bisect start <commit>^1 <commit>^2
    ```
    ^ This starts a classical bisect inside a PR.

    ```sh
    git bisect run <test-command>
    # OR
    git bisect bad/good
    ```

4. Success!

'
